name: Deploy

on:
  push:
    branches:
      - master
    tags:    
      - 'v*'

jobs:
  test:
    uses: ./.github/workflows/ci.yml  # use the callable tests job to run tests
  deploy:
    name: Push Docker image to Docker Hub
    needs: [test]  # require tests to pass before deploy runs
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/gburgett/linkscanner
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}